# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

permissions:
  contents: read
  pull-requests: write
  
on:
  push:
  pull_request:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: "true"

jobs:
  frontend:
    name: Frontend (Node ${{ matrix.node-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest] 
        # Don't use Windows or Mac for CI to reduce costs
        # RHEL, openSUSE, and Debian aren't supported at GitHub Actions
        # Learn more about self-hosted runners at https://www.youtube.com/watch?v=aLHyPZO0Fy0
        node-version: [24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    - name: Frontend Install
      run: npm ci
      working-directory: frontend
    - name: Frontend Build
      run: npm run build
      working-directory: frontend
    - name: Frontend Test
      run: npm test --if-present
      working-directory: frontend
  
  backend:
    name: Backend (Node ${{ matrix.node-version }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-slim] 
        # Don't use Windows or Mac for CI to reduce costs
        # RHEL, openSUSE, and Debian aren't supported at GitHub Actions
        # Learn more about self-hosted runners at https://www.youtube.com/watch?v=aLHyPZO0Fy0
        node-version: [24.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/


    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Backend Install
        run: npm ci
        working-directory: backend

      - name: Backend Build
        run: npm run build --if-present
        working-directory: backend

      - name: Backend Test
        run: npm test --if-present
        working-directory: backend
